import streamlit as st
import pandas as pd
import requests

# Set page configuration
st.set_page_config(page_title="Agent Mail Interface", layout="wide")

st.title("Demonstration of LangGraph Power")
st.markdown("Connects to the Multi-Agent System on port 4000")

# ---------- USER Metadata ----------
st.sidebar.header("Personal Metadata")
with st.sidebar :
    first_name = st.text_input('First Name', value="Yann")
    last_name = st.text_input('Last Name', value="L'Hotelier")
    company = st.text_input('Compagnie', value="BHT")
    role = st.text_input('Role', value="Master Data Science student")

user_metadata = (
    f"First Name: {first_name}\n"
    f"Last Name: {last_name}\n"
    f"Company: {company}\n"
    f"Role: {role}"
)
# ---------- MAIN: Input Section ----------
st.markdown("---")
st.header("📧 Incoming Email")
st.markdown("Enter the raw email content below to test the agent's capabilities.")

sender_email = st.text_input("Sender Email", value="customer@example.com")
email_id = st.text_input("Email ID", value="test-001")    
email_content = st.text_area(
    "Email Content:", 
    height=200, 
    placeholder="Paste the email text here (e.g., 'Your invoice seems wrong...')"
)

# ---------- ACTION: Send to Agent ----------
if st.button("Send to Agent"):
    if not email_content.strip():
        st.warning("Please enter some email content before sending.")
    else:
        # 1. Prepare Payload
        payload = {
            "email_content": email_content,
            "sender_email": sender_email,
            "email_id": email_id,
            "user_metadata": user_metadata,
        }
        
        # 2. Define API Endpoint
        api_url = "http://127.0.0.1:4000/invoke"
        
        # 3. Network Request
        with st.spinner('Agent is analyzing the email...'):
            try:
                response = requests.post(api_url, json=payload)
                
                # Check for successful response
                if response.status_code == 200:
                    try:
                        output_json = response.json()
                        st.success("Analysis complete! ✅")
                        
                        # ---------- OUTPUT: LangGraph Response ----------
                        st.markdown("---")
                        st.header('LangGraph Response')
                        
                        # Section 1: Classification
                        if "classification" in output_json:
                            st.subheader("🔍 Classification")
                            classification = output_json["classification"]
                            df_classif = pd.DataFrame([classification])
                            summary = df_classif['summary'][0]
                            df_classif.drop(columns='summary', inplace = True)
                            st.table(df_classif)
                            st.subheader("Summary")
                            st.markdown(summary)
                        
                        # Section 2: AI Advice / Interrupts
                        if "__interrupt__" in output_json and output_json["__interrupt__"]:
                            try:
                                action = output_json["__interrupt__"][0]["value"]["action"]
                                st.subheader("⚡ AI Advice")
                                st.markdown(f"<div style='padding:10px; background-color:#ffeeba; border-radius:5px; color:#856404;'><b>Action Required:</b> {action}</div>", unsafe_allow_html=True)
                            except (KeyError, IndexError):
                                pass

                        # Section 3: Draft Response
                        if "draft_response" in output_json:
                            st.subheader("✏️ Draft Response")
                            st.text_area(
                                "Draft generated by AI:", 
                                value=output_json["draft_response"], 
                                height=350
                            )
                            
                            col_rove, col_reject = st.columns([1, 4])
                            with col_rove:
                                if st.button("rove & Send"):
                                    st.balloons()
                                    st.success("Email sent successfully simulated!")

                    except requests.exceptions.JSONDecodeError:
                        st.error("Agent returned 200 OK but invalid JSON.")
                        st.code(response.text)

                else:
                    # --- THIS IS THE FIX ---
                    st.error(f"Agent Error: Received status code {response.status_code}")
                    st.markdown("**Debug Info (Copy this for your colleague):**")
                    # We use .text instead of .json() to show the raw error traceback
                    st.code(response.text) 
                        
            except requests.exceptions.ConnectionError:
                st.error("❌ Connection Failed")
                st.markdown("""
                **Could not connect to the agent.** Please ensure the backend is running:
                1. Open a terminal in `src/multi-agent-system`
                2. Run `uv run uvicorn main:fastapi_ --reload --port 4000`
                """)
            except Exception as e:
                st.error(f"An unexpected error occurred: {e}")