import streamlit as st
import pandas as pd
import json 
import random
import os
# # Input data
# input_json = {
#   "email_content": "Your invoice seems wrong, please fix it.",
#   "sender_email": "customer@example.com",
#   "email_id": "1"
# }
# # Output data (from langgraph)
# output_json = {
#   "email_content": "Your invoice seems wrong, please fix it.",
#   "sender_email": "customer@example.com",
#   "email_id": "1",
#   "classification": {
#     "intent": "complex",
#     "urgency": "high",
#     "topic": "billing/invoice",
#     "summary": "The customer indicates that the invoice they received appears to be incorrect and is requesting that the mistake be corrected promptly."
#   },
#   "draft_response": "Subject: Re: Issue with Your Invoice – We’ll Resolve This Immediately\n\nDear [Customer Name],\n\nThank you for bringing the invoice discrepancy to our attention. I’m sorry for any inconvenience this has caused and want to assure you that we will correct it as quickly as possible.\n\nTo help us identify the issue, could you please provide the following:\n1. Invoice number (or issue date)\n2. Description of what looks incorrect\n3. Any supporting documents (PDF invoice, PO, receipt)\n\nOnce received, our finance team will review and issue a corrected invoice (or credit memo) within 1 business day.\n\nFeel free to call our Billing Support line at 1-800-555-0199 if you need immediate assistance.\n\nThank you,\n[Your Name]\nBilling Support",
#   "messages": [
#     {
#       "type": "human",
#       "content": "Processing email: Your invoice seems wrong, please fix it."
#     }
#   ],
#   "__rupt__": [
#     {
#       "value": {
#         "email_id": "1",
#         "original_email": "Your invoice seems wrong, please fix it.",
#         "draft_response": "Subject: Re: Issue with Your Invoice – We’ll Resolve This Immediately\n\nDear [Customer Name]...\n\n(BODY)...",
#         "urgency": "high",
#         "intent": "complex",
#         "action": "Please review and approve/edit this response"
#       }
#     }
#   ]
# }

script_dir = os.path.dirname(os.path.abspath(__file__))
json_path = os.path.join(script_dir, "streamlit_ui", "llmspeech.json")
with open(json_path, "r") as f:
    emails = json.load(f)
selected_email = random.choice(emails)

input_json = selected_email["input_json"]
output_json = selected_email["output_json"]

st.title("Demonstration of langGraph power")

# ---------- UI ----------
st.markdown("---")
st.header("📧 Incoming Email")

col1, col2 = st.columns(2)
with col1:
    st.subheader("Sender")
    st.text(input_json['sender_email'])
with col2:
    st.subheader("Email ID")
    st.text(input_json['email_id'])

with st.expander("📝 Email Content", expanded=True):
    st.markdown(f"<p style='font-size:18px'>{input_json['email_content']}</p>", unsafe_allow_html=True)

# ---------- LangGraph response section ----------
st.markdown("---")
st.header('LangGraph response')

# Classification block
st.subheader("🔍 Classification")
classification = output_json["classification"]
df_classif = pd.DataFrame({
    "Intent": [classification["intent"]],
    "Urgency": [classification["urgency"]],
    "Topic": [classification["topic"]],
    "Summary": [classification["summary"]]
})

st.dataframe(df_classif.head(1), width=1000, height=75) 

st.subheader("⚡ AI Advice")
action = output_json["__interrupt__"][0]["value"]["action"]
st.markdown(f"<span style='color:red'>{action}</span>", unsafe_allow_html=True)

st.subheader("✏️ Draft Response")
st.text_area("Draft response generated by the AI", output_json["draft_response"], height=300)

if st.button("Send after reviewing and editing"):
    st.balloons()
    st.success("The email has been sent! ✅")